### ISSUE TITLE
Can not find module 'gulp-louis'

### ISSUE THREAD

**Issue by Andi-Lo** [AvraamMavridis/gulp-louis#1]
Hi there,

I followed your instructions but cannot get this package to work. Geting the error message: "Cannot find module gulp-louis"?

![gulp-louis](https://cloud.githubusercontent.com/assets/7545568/6872363/0b0cbefc-d4a9-11e4-9dff-2702e9c19dba.jpg)

Any idea whats wrong?

Greetings

**Comment by AvraamMavridis** [comment]
@bitHugger Hi Andreas, I will test it and let you know. Thx for the feedback ;)

**Comment by mcellier** [comment]
Same here, any update ?

**Comment by AvraamMavridis** [comment]
Hi @mcellier , I will try to find some time during the weekend to fix it. Thx.

**Comment by AvraamMavridis** [comment]
@mcellier @Andi-Lo I dont have time to fix it, but its open for a PR :)
