### ISSUE TITLE
Remove gulp dependency

### ISSUE THREAD

**Issue by stefanjudis** [AvraamMavridis/gulp-louis#10]
Hey hey - this looks really nice.

What about removing the gulp dependency before more work goes into it.

People using `npm scripts`, `brocolli`, `grunt` might like it. ;)

**Comment by AvraamMavridis** [comment]
:+1:

**Comment by stefanjudis** [comment]
What about you opening another repo which is just `louis` and I'll do a PR there ( will be a big one though )?

`gulp-louis` should only be a wrapper around that one then. :) ( if you agree - don't want to be pushy or anything ).

**Comment by AvraamMavridis** [comment]
Yap, I agree. I dont have time to do it now, but I will do it tomorrow morning for sure.

**Comment by stefanjudis** [comment]
:+1: Nice evening then.

**Comment by AvraamMavridis** [comment]
Close issue because of https://github.com/AvraamMavridis/louis/issues/1
