### ISSUE TITLE
Phantomas path bug

### ISSUE THREAD

**Issue by theotherzach** [AvraamMavridis/gulp-louis#11]
When attempting to run `gulp-louis` with the following config:

``` json
{
  "url": "http://localhost:8000/",
  "timeout": 60,
  "performanceBudget": {
    "requests": 2,
    "medianLatency": 10,
    "slowestResponse": 1000
  }
}
```

I get the following error: 

```
{ [Error: Command failed: /bin/sh -c /Users/zach/Code/my-cool-project/node_modules/gulp-louis/node_modules/.bin/phantomas http://localhost:8000/ --engine webkit --runs 1 --timeout 60 --viewport 1280x1024 --reporter=json > results.json
/bin/sh: /Users/zach/Code/my-cool-project/node_modules/gulp-louis/node_modules/.bin/phantomas: No such file or directory
]
```

I assume that this is a problem because my project's dependencies do not download their `devDependencies` during an `npm install`. See [this](https://docs.npmjs.com/files/package.json#devdependencies).

I suspect that the issue was introduced in this [PR](https://github.com/AvraamMavridis/gulp-louis/pull/2/files#diff-7e3ad6eaa0dbf561a6b14eaba40b3b45L17).

I'm going to fork the repo and try adding `phantomas` as a dependency rather than as a devDependency. If that works and you consider it an acceptable solution, I'll create a PR.

**Comment by theotherzach** [comment]
PR mentioned: https://github.com/AvraamMavridis/gulp-louis/pull/2/files#diff-7e3ad6eaa0dbf561a6b14eaba40b3b45L17

**Comment by AvraamMavridis** [comment]
@theotherzach sure, if it works, make the PR and I will merge it and bump the version. Thx!

**Comment by thasmo** [comment]
Got the same problem.

**Comment by AvraamMavridis** [comment]
@thasmo Thx, I will check it during the week.

**Comment by AvraamMavridis** [comment]
1.1.0 should solve the issue.
