### ISSUE TITLE
Performance metric don't seem reliable

### ISSUE THREAD

**Issue by janjaap** [AvraamMavridis/gulp-louis#19]
I've run this tools against multiple websites and compared that with the reports of webpagetest.org and what the Chrome Developer Tools show me. The results of webpagetest are pretty close to what I get reported by gulp-louis in the json output, but it's way off when compared to the Chrome Dev Tools. Certainly where html, css and js size is concerned.

Can it be that some calculations (additions, subtractions) are done for those particular metrics?

**Comment by janjaap** [comment]
Never mind. It's Phantomas/Phantomjs that's unreliable: https://github.com/macbre/phantomas/blob/devel/modules/assetsTypes/assetsTypes.js#L5

**Comment by AvraamMavridis** [comment]
@janjaap good to know. thx.

**Comment by janjaap** [comment]
It might have something to do with gzip encoding acceptance headers. I'm looking into that currently. This is most likely a setting that has to change on the Phantomas side.

**Comment by AvraamMavridis** [comment]
@janjaap let me know if you find something more. If this setting can be passed to Phantomas through command line we can add it here as well.

**Comment by janjaap** [comment]
@AvraamMavridis I've tested another tool, Sitespeed.io, and that tool, however also based on PhantomJS, delivers results that are way more accurate that the gulp-louis | phantomas | phantomjs stack. Which leads me to think that Phantomas is the culprit here and not PhantomJS or gulp-louis.

**Comment by AvraamMavridis** [comment]
@janjaap you are probably right. My plan is to work on another tool/cli that will not use Phantomas. Hopefully in the next 1-2 months.
