### ISSUE TITLE
url option not working

### ISSUE THREAD

**Issue by cmstroscio** [AvraamMavridis/gulp-louis#22]
Hello, Really cool tool, thanks! When I try to add a url, I get an error. It looks like it may be adding .json onto the url [www.google.com/.json].
<img width="1678" alt="screen shot 2017-04-21 at 2 15 14 pm" src="https://cloud.githubusercontent.com/assets/6492324/25290723/24b8b912-269d-11e7-9faf-579670a07817.png">

Here's how I have it set up: 
<img width="559" alt="screen shot 2017-04-21 at 2 16 48 pm" src="https://cloud.githubusercontent.com/assets/6492324/25290741/3b8b7652-269d-11e7-9ecb-4e920f84e65f.png">

Not sure if I'm doing something wrong or if there is a a bug. It runs fine without a url.

Thanks
Marshall

**Comment by AvraamMavridis** [comment]
I will have a look as soon as possible, thx @cmstroscio

**Comment by brianO3world** [comment]
@AvraamMavridis any word on this? I'm seeing the same error when I add a URL.

**Comment by AvraamMavridis** [comment]
Hi @brianO3world I will try to look at it during the next week, sorry for that.

**Comment by brianO3world** [comment]
excellent, @AvraamMavridis! thanks for the quick reply :-) look forward to seeing what you come up with

**Comment by AvraamMavridis** [comment]
@brianO3world @cmstroscio the issue should be fixed in the `2.3.2` 
Let me know if you face any other issue, would be nice if you can provide a minimal project or example with your setup, I don't use gulp anymore so its kinda tricky for me to re-produce possible bugs.

**Comment by brianO3world** [comment]
@avraam-mavridis-sociomantic had the chance to take the 2.3.2 update for a test drive this AM, but it seems to be producing the same error.

This is the standalone gulp task I have setup

```
gulp.task('louis', function() {
    louis({
        url: 'http://www.google.com/',
        timeout: 200,
        viewport: '1280x1024',
        engine: 'webkit',
        userAgent: 'Chrome/37.0.2062.120',
        noExternals: false,
        performanceBudget: {
            requests: 2,
            medianLatency: 10,
            slowestResponse: 1000,
            cssSize: 200,
            jsSize: 2000,
            consoleMessages: 0,
            imageSize: 5000,
            domContentLoaded: 2000,
            smallestLatency: 1000
        }
    });
});
```

Here is the error I'm getting when I run that task:

```
{ Error: Command failed: node node_modules/phantomas/bin/phantomas.js http://www.google.com/ --runs 1 --timeout 200 --viewport 1280x1024 --reporter=json > www.google.com.json
phantomas: (255) Failed to parse JSON with the results

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
  killed: false,
  code: 255,
  signal: null,
  cmd: 'node node_modules/phantomas/bin/phantomas.js http://www.google.com/ --runs 1 --timeout 200 --viewport 1280x1024 --reporter=json > www.google.com.json' }
```

Same warning with it trying to find a JSON file at the URL I specify.

Thoughts?

UPDATE: I did just notice that this time it created a `www.google.com.json` file at the the root of my project, but it's blank.

**Comment by brianO3world** [comment]
@avraam-mavridis-sociomantic any thoughts on this?

**Comment by brianO3world** [comment]
@avraam-mavridis-sociomantic have you had a chance to take another look at this?

**Comment by AvraamMavridis** [comment]
Hi @brianO3world  sorry, I didnt have time to take a look at it. You can always open a PR if you have a fix, I will try to look at it as soon as possible, but I cant promise anything unfortunately.
