### ISSUE TITLE
Graph representation of the requests

### ISSUE THREAD

**Issue by AvraamMavridis** [AvraamMavridis/gulp-louis#9]
Display the various metrics in a graphical representation. e.g. charts

**Comment by stefanjudis** [comment]
One question - you want to put graphs inside of the CLI?

In case you want to start rendering HTML I'm maintaining https://github.com/stefanjudis/grunt-phantomas which generates a detailed report on top of phantomas

http://stefanjudis.github.io/grunt-phantomas/gruntjs/

I also made the mistake of having a hard build system dependency...

Maybe we can collaborate somehow, when you're going into the same direction. :bowtie:

**Comment by AvraamMavridis** [comment]
Hey @stefanjudis sure! I will try too have a look at grunt-phantomas during the weekend.
Actually the whole package was inspired by one of your talks, before around a year at co_up, I was using gulp and there wasnt something related back then, so I did that small package on top of phantomas but I didnt have time to move it a bit forward. I am open to any suggestions or if you are planning to create a new tool or any ideas or PRs on that or anything else of course I can help :)

**Comment by stefanjudis** [comment]
:blush: 

Glad you liked the talk. :)

As a "tiny" recommendation I'd continue this package with #10. I made the mistake twice - and it really bites you in case your module gets some attention. :)

I can help with that if you like. :bowtie: 

> I am open to any suggestions or if you are planning to create a new tool or any ideas or PRs on that or anything else of course I can help.

Yeah maybe let's chat at up.front or something. I'd love to start collaboration on a nice UI on top of phantomas ( new project, old project, whatever ;) ).

For me `louis` looks already pretty good as a CLI tool - I wouldn't put a rendered UI in here tbh. Just makes it harder to maintain and a bigger codebase. Maybe another module on top `louis` would do the job. ;)

**Comment by AvraamMavridis** [comment]
Yes sure go for #10 if you want. I agree that is better to create another module.
Are you planning to attend any meetup event soon? Or when is the next Web Performance Group meetup?

**Comment by stefanjudis** [comment]
planned up.front next week.

Next webperf meetup will probably be in January.

**Comment by AvraamMavridis** [comment]
I will be in the next up.front as well. If I'll see you I will come to talk you ;)

**Comment by AvraamMavridis** [comment]
Close as this will/can be part of another project. Luis will kept simple.
